import { SubscriptionBillingPeriod } from "~/application/enums/subscriptions/SubscriptionBillingPeriod";
import { SubscriptionPriceType } from "~/application/enums/subscriptions/SubscriptionPriceType";
import { DefaultFeatures } from "../dtos/shared/DefaultFeatures";
import { SubscriptionProductDto } from "../dtos/subscriptions/SubscriptionProductDto";
import { PricingModel } from "../enums/subscriptions/PricingModel";
import { SubscriptionFeatureLimitType } from "../enums/subscriptions/SubscriptionFeatureLimitType";

const currency = "usd";
const plans: SubscriptionProductDto[] = [
  {
    stripeId: "",
    order: 1,
    title: "pricing.products.plan1.title",
    description: "pricing.products.plan1.description",
    model: PricingModel.FLAT_RATE,
    public: true,
    prices: [
      {
        stripeId: "",
        subscriptionProductId: "",
        type: SubscriptionPriceType.RECURRING,
        billingPeriod: SubscriptionBillingPeriod.MONTHLY,
        price: 0,
        currency,
        trialDays: 0,
        active: true,
      },
      {
        stripeId: "",
        subscriptionProductId: "",
        type: SubscriptionPriceType.RECURRING,
        billingPeriod: SubscriptionBillingPeriod.YEARLY,
        price: 0,
        currency,
        trialDays: 0,
        active: true,
      },
    ],
    features: [
      {
        order: 1,
        title: "3 users",
        name: DefaultFeatures.Users,
        value: 2,
        type: SubscriptionFeatureLimitType.MAX,
      },
      {
        order: 2,
        title: "5 project",
        name: "project",
        value: 1,
        type: SubscriptionFeatureLimitType.MAX,
      },
      {
        order: 3,
        title: "Talents Pool",
        name: "talents",
        value: 0,
        type: SubscriptionFeatureLimitType.NOT_INCLUDED,
      },
      {
        order: 4,
        title: "API",
        name: DefaultFeatures.API,
        value: 0,
        type: SubscriptionFeatureLimitType.NOT_INCLUDED,
      },
      {
        order: 5,
        title: "Priority support",
        name: DefaultFeatures.PrioritySupport,
        value: 0,
        type: SubscriptionFeatureLimitType.NOT_INCLUDED,
      },
    ],
    badge: "",
    active: true,
  },
  {
    stripeId: "",
    order: 2,
    title: "pricing.products.plan2.title",
    description: "pricing.products.plan2.description",
    public: true,
    model: PricingModel.FLAT_RATE,
    prices: [
      {
        stripeId: "",
        subscriptionProductId: "",
        type: SubscriptionPriceType.RECURRING,
        billingPeriod: SubscriptionBillingPeriod.MONTHLY,
        price: 49,
        currency,
        trialDays: 30,
        active: true,
      },
      {
        stripeId: "",
        subscriptionProductId: "",
        type: SubscriptionPriceType.RECURRING,
        billingPeriod: SubscriptionBillingPeriod.YEARLY,
        price: 499,
        currency,
        trialDays: 0,
        active: true,
      },
    ],
    features: [
      {
        order: 1,
        title: "7 users",
        name: DefaultFeatures.Users,
        value: 7,
        type: SubscriptionFeatureLimitType.MAX,
      },
      {
        order: 2,
        title: "50 projects",
        name: "project",
        value: 50,
        type: SubscriptionFeatureLimitType.UNLIMITED,
      },
      {
        order: 3,
        title: "100 Talents Pool",
        name: "talents",
        value: 100,
        type: SubscriptionFeatureLimitType.MAX,
      },
      {
        order: 4,
        title: "API",
        name: DefaultFeatures.API,
        value: 0,
        type: SubscriptionFeatureLimitType.NOT_INCLUDED,
      },
      {
        order: 5,
        title: "Priority support",
        name: DefaultFeatures.PrioritySupport,
        value: 0,
        type: SubscriptionFeatureLimitType.NOT_INCLUDED,
      },
    ],
    badge: "pricing.recommended",
    active: true,
  },
  {
    stripeId: "",
    order: 3,
    title: "pricing.products.plan3.title",
    description: "pricing.products.plan3.description",
    public: true,
    model: PricingModel.FLAT_RATE,
    prices: [
      {
        stripeId: "",
        subscriptionProductId: "",
        type: SubscriptionPriceType.RECURRING,
        billingPeriod: SubscriptionBillingPeriod.MONTHLY,
        price: 119,
        currency,
        trialDays: 30,
        active: true,
      },
      {
        stripeId: "",
        subscriptionProductId: "",
        type: SubscriptionPriceType.RECURRING,
        billingPeriod: SubscriptionBillingPeriod.YEARLY,
        price: 1190,
        currency,
        trialDays: 0,
        active: true,
      },
    ],
    features: [
      {
        order: 1,
        title: "30 users",
        name: DefaultFeatures.Users,
        value: 30,
        type: SubscriptionFeatureLimitType.MAX,
      },
      {
        order: 2,
        title: "Unlimited Projects",
        name: "project",
        value: 0,
        type: SubscriptionFeatureLimitType.UNLIMITED,
      },
      {
        order: 3,
        title: "Unlimited Talents Pool",
        name: "talents",
        value: 0,
        type: SubscriptionFeatureLimitType.INCLUDED,
      },
      {
        order: 4,
        title: "API",
        name: DefaultFeatures.API,
        value: 0,
        type: SubscriptionFeatureLimitType.UNLIMITED,
      },
      {
        order: 5,
        title: "Priority support",
        name: DefaultFeatures.PrioritySupport,
        value: 0,
        type: SubscriptionFeatureLimitType.INCLUDED,
      },
    ],
    badge: "",
    active: true,
  },
];

export default plans;
