import { useTranslation } from "react-i18next";
import EmptyState from "~/components/ui/emptyState/EmptyState";
import DateUtils from "~/utils/shared/DateUtils";
import { useState } from "react";
import clsx from "~/utils/shared/ClassesUtils";
import ButtonTertiary from "../ui/buttons/ButtonTertiary";
import { Link } from "remix";
import { useAdminData } from "~/utils/data/useAdminData";
import EntityIcon from "../layouts/icons/EntityIcon";
import CheckIcon from "../ui/icons/CheckIcon";
import XIcon from "../ui/icons/XIcon";
import { EntityWithCount } from "~/utils/db/entities/entities.db.server";
import InputSearch from "../ui/input/InputSearch";

interface Props {
  items: EntityWithCount[];
}

type Header = {
  title: string;
  name?: string;
  sortable?: boolean;
};

export default function EntitiesTable({ items }: Props) {
  const { t } = useTranslation();
  const adminData = useAdminData();

  const [searchInput, setSearchInput] = useState("");

  const filteredItems = () => {
    if (!items) {
      return [];
    }
    return items.filter(
      (f) =>
        DateUtils.dateYMDHMS(f.createdAt)?.toString().toUpperCase().includes(searchInput.toUpperCase()) ||
        f.slug?.toString().toUpperCase().includes(searchInput.toUpperCase()) ||
        f.title?.toString().toUpperCase().includes(searchInput.toUpperCase()) ||
        f.titlePlural?.toString().toUpperCase().includes(searchInput.toUpperCase())
    );
  };

  const [sortByColumn, setSortByColumn] = useState("order");
  const [sortDirection, setSortDirection] = useState(-1);

  const headers: Header[] = [
    {
      name: "title",
      title: t("models.entity.object"),
    },
    {
      name: "prefix",
      title: t("models.entity.prefix"),
    },
    {
      name: "properties",
      title: t("models.entity.properties"),
    },
    {
      title: t("models.entity.rows"),
    },
    {
      title: t("models.entity.isFeature"),
    },
    {
      title: t("models.entity.isAutogenerated"),
    },
    {
      title: t("models.entity.hasApi"),
    },
    {
      title: t("models.entity.requiresLinkedAccounts"),
    },
    {
      title: t("shared.actions"),
    },
  ];

  function sortBy(column: string | undefined) {
    if (column) {
      setSortDirection(sortDirection === -1 ? 1 : -1);
      setSortByColumn(column);
    }
  }

  const sortedItems = () => {
    if (!filteredItems()) {
      return [];
    }
    const column = sortByColumn;
    if (!column) {
      return filteredItems();
    }
    return filteredItems()
      .slice()
      .sort((x, y) => {
        if (x[column] && y[column]) {
          if (sortDirection === -1) {
            return (x[column] > y[column] ? 1 : -1) ?? 1;
          } else {
            return (x[column] < y[column] ? 1 : -1) ?? 1;
          }
        }
        return 1;
      });
  };

  function getEntitySlug(item: EntityWithCount) {
    if (adminData.myTenants.length > 0) {
      return `/app/${adminData.myTenants[0].tenant.slug}/${item.slug}`;
    }
    return "";
  }

  return (
    <div className="space-y-2">
      <InputSearch value={searchInput} setValue={setSearchInput} />
      <div>
        {(() => {
          if (sortedItems().length === 0) {
            return (
              <div>
                <EmptyState
                  className="bg-white"
                  captions={{
                    thereAreNo: t("shared.noRecords"),
                  }}
                  icon="plus"
                />
              </div>
            );
          } else {
            return (
              <div className="flex flex-col">
                <div className="overflow-x-auto">
                  <div className="py-2 align-middle inline-block min-w-full">
                    <div className="shadow overflow-hidden border border-gray-200 sm:rounded-lg">
                      <table className="min-w-full divide-y divide-gray-200">
                        <thead className="bg-gray-50">
                          <tr>
                            {headers.map((header, idx) => {
                              return (
                                <th
                                  key={idx}
                                  onClick={() => sortBy(header.name)}
                                  scope="col"
                                  className={clsx(
                                    "px-2 py-2 truncate text-left text-xs font-medium text-gray-500 tracking-wider select-none",
                                    header.name && "cursor-pointer hover:text-gray-700"
                                  )}
                                >
                                  <div className="flex items-center space-x-1 text-gray-500">
                                    <div>{header.title}</div>
                                    <div className={clsx((!header.name || sortByColumn !== header.name) && "invisible")}>
                                      {(() => {
                                        if (sortDirection === -1) {
                                          return (
                                            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                              <path
                                                fillRule="evenodd"
                                                d="M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z"
                                                clipRule="evenodd"
                                              />
                                            </svg>
                                          );
                                        } else {
                                          return (
                                            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                              <path
                                                fillRule="evenodd"
                                                d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                                clipRule="evenodd"
                                              />
                                            </svg>
                                          );
                                        }
                                      })()}
                                    </div>
                                  </div>
                                </th>
                              );
                            })}
                          </tr>
                        </thead>
                        {sortedItems().map((item, idx) => {
                          return (
                            <tbody key={idx} className="bg-white divide-y divide-gray-200">
                              <tr className=" text-gray-600">
                                <td className="w-full px-2 py-2 whitespace-nowrap text-gray-700 text-sm">
                                  <div className="flex items-center space-x-3">
                                    {/* <div className="w-10 h-10 rounded-md p-2 border bg-gray-50 border-gray-200 shadow-sm flex items-center justify-center">
                                      {item.icon ? (
                                        <EntityIcon className="h-6 w-6 text-gray-700" icon={item.icon} title={item.title} />
                                      ) : (
                                        <span className="text-gray-700">?</span>
                                      )}
                                    </div> */}
                                    <div className="flex flex-col">
                                      <div>
                                        {t(item.title)}{" "}
                                        <span>
                                          {item.active ? (
                                            <span className="text-teal-500 text-xs">{/* ({t("shared.active")}) */}</span>
                                          ) : (
                                            <span className="text-red-500 text-xs">({t("shared.inactive")})</span>
                                          )}
                                        </span>
                                        {/* <span className="text-gray-400 italic">({t(item.titlePlural)})</span>{" "} */}
                                      </div>
                                      {item.active && item.isAutogenerated && getEntitySlug(item) ? (
                                        <Link to={getEntitySlug(item)} className="underline text-gray-800">
                                          {item.slug}
                                        </Link>
                                      ) : (
                                        <span className="text-gray-800">{item.slug}</span>
                                      )}{" "}
                                    </div>
                                  </div>
                                </td>
                                <td className="px-2 py-2 whitespace-nowrap text-sm">{item.prefix}</td>
                                <td className="px-2 py-2 whitespace-nowrap text-sm max-w-sm truncate">
                                  {item.properties.filter((f) => !f.isDefault).length > 0 ? (
                                    <Link
                                      className="  pb-1 border-b border-accent-400 border-dashed hover:border-dotted truncate"
                                      to={"/admin/entities/" + item.slug + "/properties"}
                                    >
                                      {item.properties
                                        .filter((f) => !f.isDefault)
                                        .map((f) => t(f.title))
                                        .join(", ")}
                                    </Link>
                                  ) : (
                                    <Link
                                      className="max-w-sm pb-1 border-b border-red-400 border-dashed hover:border-dotted truncate"
                                      to={"/admin/entities/" + item.slug + "/properties"}
                                    >
                                      {t("shared.notSet")}
                                    </Link>
                                  )}
                                </td>
                                <td className="px-2 py-2 whitespace-nowrap text-sm">
                                  <Link to={"/admin/entities/" + item.slug + "/rows"}>{item._count.rows}</Link>
                                </td>
                                <td className="px-2 py-2 whitespace-nowrap text-sm">
                                  <span>{item.isFeature ? <CheckIcon className="h-4 w-4 text-teal-500" /> : <XIcon className="h-4 w-4 text-gray-400" />}</span>
                                </td>
                                <td className="px-2 py-2 whitespace-nowrap text-sm">
                                  <span>
                                    {item.isAutogenerated ? <CheckIcon className="h-4 w-4 text-teal-500" /> : <XIcon className="h-4 w-4 text-gray-400" />}
                                  </span>
                                </td>
                                <td className="px-2 py-2 whitespace-nowrap text-sm">
                                  <span>{item.hasApi ? <CheckIcon className="h-4 w-4 text-teal-500" /> : <XIcon className="h-4 w-4 text-gray-400" />}</span>
                                </td>
                                <td className="px-2 py-2 whitespace-nowrap text-sm">
                                  <span>
                                    {item.requiresLinkedAccounts ? (
                                      <CheckIcon className="h-4 w-4 text-teal-500" />
                                    ) : (
                                      <XIcon className="h-4 w-4 text-gray-400" />
                                    )}
                                  </span>
                                </td>
                                <td className="px-2 py-2 whitespace-nowrap text-sm">
                                  <ButtonTertiary to={"/admin/entities/" + item.slug + "/details"}>{t("shared.edit")}</ButtonTertiary>
                                </td>
                              </tr>
                            </tbody>
                          );
                        })}
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            );
          }
        })()}
      </div>
    </div>
  );
}
