import clsx from "clsx";
import CheckIcon from "../ui/icons/CheckIcon";

const groups = [
  {
    headline: "Rock-solid features 🚀",
    subheadline: "A rock-solid starter kit",
    description: "Everything you need to start to build an MVP in 1 day, or to build a whole SaaS application in a few weeks.",
    items: [
      {
        name: "Authentication",
        description: "Log in, Sign up, Forgot password, Reset password, and Magic-link out-of-the-box pages.",
      },
      { name: "Subscriptions", description: "Create flat rate or per user subscriptions with Stripe products, checkout, and payments." },
      {
        name: "Blogging",
        description: "Manage your blog posts using markdown content + SEO tools.",
      },
      { name: "Account Settings", description: "Let your SaaS users update their account, members, subscription, organization settings and more." },
      { name: "Admin Portal", description: "Set up your pricing plans + email templates and manage your Tenants and Users." },
      { name: "Audit Trails", description: "Track the application usage based on Events (Created, Updated, and Deleted)." },
      { name: "Entity Builder", description: "Custom properties, Instant API, API Keys manager, Autogenerated Views/Forms, Workflows, and Webhooks." },
      { name: "Components", description: "Inputs, Tables, Buttons, Page layouts, Sidebar menus, Modal Dialogs..." },
      { name: "Documentation", description: "Markdown tutorials... TODO" },
    ],
  },
  {
    headline: "First-class tech stack 💪",
    subheadline: "Powered by the best tools",
    description: "The codebase comes with the latest technology out there: SSR (Remix), utility-first design (Tailwind CSS), and the best ORM (Prisma).",
    items: [
      {
        name: "Remix",
        description: "Focused on web standards and modern web app UX, you’re simply going to build better websites.",
      },
      { name: "React", description: "A JavaScript library for building user interfaces." },
      {
        name: "Tailwind CSS",
        description: "Rapidly build modern websites without ever leaving your HTML.",
      },
      { name: "Prisma", description: "Next-generation Node.js and TypeScript ORM." },
    ],
  },
  {
    headline: "Integrations 🔗",
    subheadline: "Connect with your apps",
    description: "Using Webhooks by Zapier, integrate with +4,000 apps, such as Notion, Airtable, Google Sheets/Docs, and more.",
    items: [
      {
        name: "Stripe",
        description: "The payments infrastructure for the internet.",
      },
      { name: "Postmark", description: "The email delivery service that people actually like." },
      {
        name: "Webhooks",
        description: "Hook with Zapier by using the Custom Entity events (Created, Updated, and Deleted).",
      },
    ],
  },
];

export default function Features() {
  return (
    <div id="features">
      {groups.map((group) => {
        return (
          <div key={group.headline} className="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:px-8 lg:grid lg:grid-cols-3 lg:gap-x-8">
            <div>
              <h2 className="text-base font-semibold text-theme-600 uppercase tracking-wide">{group.subheadline}</h2>
              <p className="mt-2 text-3xl font-extrabold text-gray-900 dark:text-white">{group.headline}</p>
              <p className="mt-4 text-lg text-gray-500">{group.description}</p>
            </div>
            <div className="mt-12 lg:mt-0 lg:col-span-2">
              <dl
                className={clsx(
                  "space-y-10 sm:space-y-0 sm:grid sm:grid-cols-2 sm:grid-flow-col sm:gap-x-6 sm:gap-y-10 lg:gap-x-8",
                  group.items.length <= 4 ? "sm:grid-rows-2" : "sm:grid-rows-4"
                )}
              >
                {group.items.map((feature) => (
                  <div key={feature.name} className="relative">
                    <dt>
                      <CheckIcon className="absolute h-6 w-6 text-theme-500" aria-hidden="true" />
                      <p className="ml-9 text-lg leading-6 font-medium text-gray-900 dark:text-white">{feature.name}</p>
                    </dt>
                    <dd className="mt-2 ml-9 text-base text-gray-500">{feature.description}</dd>
                  </div>
                ))}
              </dl>
            </div>
          </div>
        );
      })}
    </div>
  );
}
