import { SideBarItem } from "./SidebarItem";
import { TenantUserType } from "~/application/enums/tenants/TenantUserType";
import { SvgIcon } from "../enums/shared/SvgIcon";
import UrlUtils from "~/utils/app/UrlUtils";
import { Params } from "react-router";
import { EntityWithDetails } from "~/utils/db/entities/entities.db.server";

export const AppSidebar = (params: Params, entities: EntityWithDetails[], isDebugMode?: boolean): SideBarItem[] => {
  const currentTenantUrl = UrlUtils.stripTrailingSlash(UrlUtils.currentTenantUrl(params));

  const entitiesItems: SideBarItem[] = [];
  entities
    .filter((f) => f.isAutogenerated)
    .forEach((entity) => {
      // const modelProperties = entity.properties.filter((f) => !f.isDynamic);
      entitiesItems.push({
        title: entity.titlePlural,
        entityIcon: entity.icon,
        // tenantUserTypes: [TenantUserType.OWNER, TenantUserType.ADMIN],
        path: `${currentTenantUrl}/` + entity.slug,
        // side: isDebugMode && SideText({ text: modelProperties.length > 0 ? "DB Model" : "Custom" }),
      });
    });
  const appItem: SideBarItem = {
    title: "",
    path: "",
    items: [
      {
        title: "app.sidebar.dashboard",
        path: `${currentTenantUrl}/dashboard`,
        icon: SvgIcon.DASHBOARD,
        tenantUserTypes: [TenantUserType.OWNER, TenantUserType.ADMIN, TenantUserType.MEMBER],
      },
      ...entitiesItems,
    ],
  };
  return [
    appItem,
    {
      title: "",
      path: "",
      items: [
        {
          title: "app.sidebar.settings",
          icon: SvgIcon.SETTINGS,
          tenantUserTypes: [TenantUserType.OWNER, TenantUserType.ADMIN],
          path: `${currentTenantUrl}/settings`,
        },
        {
          title: "app.sidebar.settings",
          icon: SvgIcon.SETTINGS,
          path: "https://github.com",
        },
        // {
        //   title: "app.sidebar.logs",
        //   icon: SvgIcon.LOGS,
        //   tenantUserTypes: [TenantUserType.OWNER, TenantUserType.ADMIN],
        //   path: `${currentTenantUrl}/logs`,
        // },
        {
          title: "admin.switchToAdmin",
          path: "/admin/dashboard",
          icon: SvgIcon.ADMIN,
          adminOnly: true,
        },
      ],
    },
  ];
};

// function SideText({ text }: { text: string }) {
//   return (
//     <div className="inline-flex justify-center space-x-1 items-center px-1.5 py-0.5 rounded-sm text-xs font-medium bg-yellow-100 text-yellow-900 italic truncate w-20">
//       <div className="truncate">{text}</div>
//     </div>
//   );
// }
