import { ActionFunction, json, LoaderFunction, redirect } from "@remix-run/node";
import { Link, useLoaderData } from "@remix-run/react";
import Constants from "~/application/Constants";
import EntityViewLayoutBadge from "~/components/entities/views/EntityViewLayoutBadge";
import PlusIcon from "~/components/ui/icons/PlusIcon";
import { i18nHelper } from "~/locale/i18n.utils";
import { updateEntity, deleteEntity, getEntityBySlug, getEntityById, EntityWithDetails } from "~/utils/db/entities/entities.db.server";
import { createEntityPermissions, deleteEntityPermissions } from "~/utils/db/permissions/permissions.db.server";
import EntityHelper from "~/utils/helpers/EntityHelper";

type LoaderData = {
  item: EntityWithDetails;
};
export let loader: LoaderFunction = async ({ params }) => {
  const item = await getEntityBySlug(params.slug ?? "");
  if (!item) {
    return redirect("/admin/entities");
  }

  const data: LoaderData = {
    item,
  };
  return json(data);
};

type ActionData = {
  error?: string;
};
const badRequest = (data: ActionData) => json(data, { status: 400 });
export const action: ActionFunction = async ({ request, params }) => {
  const { t } = await i18nHelper(request);

  const item = await getEntityBySlug(params.slug ?? "");
  if (!item) {
    return redirect("/admin/entities");
  }

  const form = await request.formData();
  const action = form.get("action")?.toString() ?? "";
  if (action === "edit") {
    const name = form.get("name")?.toString() ?? "";
    const slug = form.get("slug")?.toString().toLowerCase() ?? "";
    const order = Number(form.get("order"));
    const prefix = form.get("prefix")?.toString() ?? "";
    const title = form.get("title")?.toString() ?? "";
    const titlePlural = form.get("title-plural")?.toString() ?? "";
    const isFeature = Boolean(form.get("is-feature"));
    const isAutogenerated = Boolean(form.get("is-autogenerated"));
    const hasApi = Boolean(form.get("has-api"));
    const requiresLinkedAccounts = Boolean(form.get("requires-account-link"));
    const icon = form.get("icon")?.toString() ?? "";
    const active = Boolean(form.get("active"));

    const hasTags = Boolean(form.get("has-tags"));
    const hasComments = Boolean(form.get("has-comments"));
    const hasTasks = Boolean(form.get("has-tasks"));
    const hasWorkflow = Boolean(form.get("has-workflow"));

    const defaultVisibility = form.get("default-visibility")?.toString() ?? Constants.DEFAULT_ROW_VISIBILITY;

    const errors = await EntityHelper.validateEntity(name, slug, order, prefix, item);
    if (errors.length > 0) {
      return badRequest({ error: errors.join(", ") });
    }

    try {
      await updateEntity(item.id ?? "", {
        name,
        slug,
        order,
        prefix,
        title,
        titlePlural,
        isFeature,
        isAutogenerated,
        hasApi,
        requiresLinkedAccounts,
        icon,
        active,
        isDefault: item.isDefault,
        hasTags,
        hasComments,
        hasTasks,
        hasWorkflow,
        defaultVisibility,
      });
      if (item.name !== name) {
        await deleteEntityPermissions(item);
        const updatedEntity = await getEntityById(item.id);
        if (updatedEntity) {
          await createEntityPermissions(updatedEntity);
        }
      }

      return redirect("/admin/entities");
    } catch (e) {
      return badRequest({ error: JSON.stringify(e) });
    }
  } else if (action === "delete") {
    try {
      if (item.isDefault) {
        return badRequest({ error: "Default entities cannot be deleted" });
      }
      await deleteEntityPermissions(item);
      await deleteEntity(item.id ?? "");
      return redirect("/admin/entities");
    } catch (e) {
      return badRequest({ error: JSON.stringify(e) });
    }
  } else {
    return badRequest({ error: t("shared.invalidForm") });
  }
};

export default function EditEntityIndexRoute() {
  const data = useLoaderData<LoaderData>();
  return (
    <div>
      <div className="space-y-2">
        <div className="space-y-2 mb-3">
          <div className="flex justify-between items-center">
            <h3 className="font-medium text-sm">Views</h3>
          </div>
        </div>
      </div>

      {data.item.views.length === 0 ? <div></div> : <div></div>}

      <div className="space-y-2">
        {data.item.views
          .sort((a, b) => a.order - b.order)
          .map((item) => {
            return (
              <Link
                key={item.id}
                to={item.id}
                className="bg-white relative block w-full border-2 border-gray-300 border-dashed rounded-lg p-4 text-center hover:border-gray-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-accent-500"
              >
                <EntityViewLayoutBadge layout={item.layout} className="h-5 w-5 mx-auto text-gray-600" />
                <span className="mt-2 block text-sm font-medium text-gray-900">
                  {item.title}
                  <span className="text-xs text-gray-500 font-normal pl-1">({item.name})</span>
                  {item.isDefault && <span className="text-xs text-gray-800 font-medium pl-1"> - Default view</span>}
                </span>
              </Link>
            );
          })}

        <Link
          to={`new`}
          className="relative block w-full border-2 border-gray-300 border-dashed rounded-lg p-4 text-center hover:border-gray-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-accent-500"
        >
          <PlusIcon className="h-5 mx-auto text-gray-600" />
          <span className="mt-2 block text-sm font-medium text-gray-900">Add custom view</span>
        </Link>
      </div>
    </div>
  );
}
